[package]
name = "scoutin_frc_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
serde_json = "1.0"
serde = "1.0.228"

sqlx = { version = "0.8.6", features = [ "mysql", "runtime-tokio", "tls-native-tls" ] }
tokio = { version = "1.20.0", features = ["rt", "macros"]}